# PyCharm 友好的配置：bot 运行时没有在 localhost 上打开 docker、postgres 和 redis 端口
# 不要在生产中使用它！
version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_passwd
      - POSTGRES_DB=olgram
    ports:
      - '5400:5432'
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:6.2.7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-db:/bitnami/redis/data
    ports:
      - '6370:6379'

volumes:
  database:
  redis-db:
