# 最低服务器配置，代码从当前目录构建
version: '3'
services:
  postgres:
    image: postgres:13.4
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-db:/bitnami/redis/data
    env_file:
      - .env
  olgram:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - olgram-cert:/cert
    ports:
      - "${WEBHOOK_PORT}:80"
    depends_on:
      - postgres
      - redis

volumes:
  database:
  redis-db:
  olgram-cert:
